// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_AUTOSCREEN_H
#define UI_AUTOSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_AutoScreen
extern void ui_AutoScreen_screen_init(void);
extern void ui_AutoScreen_screen_destroy(void);
extern lv_obj_t * ui_AutoScreen;
extern lv_obj_t * ui_Panel4;
extern lv_obj_t * ui_Dropdown1;
extern void ui_event_SlowCheckbox(lv_event_t * e);
extern lv_obj_t * ui_SlowCheckbox;
extern void ui_event_MediumCheckbox(lv_event_t * e);
extern lv_obj_t * ui_MediumCheckbox;
extern void ui_event_FastCheckbox(lv_event_t * e);
extern lv_obj_t * ui_FastCheckbox;
extern void ui_event_ManualButton1(lv_event_t * e);
extern lv_obj_t * ui_ManualButton1;
extern lv_obj_t * ui_StartLabel;
extern void ui_event_ManualButton3(lv_event_t * e);
extern lv_obj_t * ui_ManualButton3;
extern lv_obj_t * ui_Label6;
extern void ui_event_ManualButton5(lv_event_t * e);
extern lv_obj_t * ui_ManualButton5;
extern lv_obj_t * ui_Label5;
// CUSTOM VARIABLES
extern lv_obj_t * uic_AutoScreen;
extern lv_obj_t * uic_Dropdown1;
extern lv_obj_t * uic_SlowCheckbox;
extern lv_obj_t * uic_MediumCheckbox;
extern lv_obj_t * uic_FastCheckbox;
extern lv_obj_t * uic_ManualButton1;
extern lv_obj_t * uic_StartLabel;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

