// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * uic_StartLabel;
lv_obj_t * uic_ManualButton1;
lv_obj_t * uic_FastCheckbox;
lv_obj_t * uic_MediumCheckbox;
lv_obj_t * uic_SlowCheckbox;
lv_obj_t * uic_Dropdown1;
lv_obj_t * uic_AutoScreen;
lv_obj_t * ui_AutoScreen = NULL;
lv_obj_t * ui_Panel4 = NULL;
lv_obj_t * ui_Dropdown1 = NULL;
lv_obj_t * ui_SlowCheckbox = NULL;
lv_obj_t * ui_MediumCheckbox = NULL;
lv_obj_t * ui_FastCheckbox = NULL;
lv_obj_t * ui_ManualButton1 = NULL;
lv_obj_t * ui_StartLabel = NULL;
lv_obj_t * ui_ManualButton3 = NULL;
lv_obj_t * ui_Label6 = NULL;
lv_obj_t * ui_ManualButton5 = NULL;
lv_obj_t * ui_Label5 = NULL;
// event funtions
void ui_event_SlowCheckbox(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_state_modify(ui_MediumCheckbox, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
        _ui_state_modify(ui_FastCheckbox, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
    }
}

void ui_event_MediumCheckbox(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_state_modify(ui_SlowCheckbox, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
        _ui_state_modify(ui_FastCheckbox, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
    }
}

void ui_event_FastCheckbox(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_state_modify(ui_SlowCheckbox, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
        _ui_state_modify(ui_MediumCheckbox, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
    }
}

void ui_event_ManualButton1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        StartAuto(e);
    }
}

void ui_event_ManualButton3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        EndAuto(e);
    }
}

void ui_event_ManualButton5(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_StartMenuScreen, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_StartMenuScreen_screen_init);
        back_button(e);
    }
}

// build funtions

void ui_AutoScreen_screen_init(void)
{
    ui_AutoScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_AutoScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel4 = lv_obj_create(ui_AutoScreen);
    lv_obj_set_width(ui_Panel4, 240);
    lv_obj_set_height(ui_Panel4, 240);
    lv_obj_set_align(ui_Panel4, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel4, 100, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Dropdown1 = lv_dropdown_create(ui_AutoScreen);
    lv_dropdown_set_options(ui_Dropdown1, "1 Minute\n3 Minutes\n5 Minutes\n10 Minutes");
    lv_obj_set_width(ui_Dropdown1, 117);
    lv_obj_set_height(ui_Dropdown1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Dropdown1, 0);
    lv_obj_set_y(ui_Dropdown1, -88);
    lv_obj_set_align(ui_Dropdown1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Dropdown1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_align(ui_Dropdown1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_align(ui_Dropdown1, LV_TEXT_ALIGN_CENTER, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_text_align(lv_dropdown_get_list(ui_Dropdown1), LV_TEXT_ALIGN_CENTER,  LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_align(lv_dropdown_get_list(ui_Dropdown1), LV_TEXT_ALIGN_CENTER,
                                LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_SlowCheckbox = lv_checkbox_create(ui_AutoScreen);
    lv_checkbox_set_text(ui_SlowCheckbox, "Slow");
    lv_obj_set_width(ui_SlowCheckbox, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SlowCheckbox, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SlowCheckbox, -5);
    lv_obj_set_y(ui_SlowCheckbox, -46);
    lv_obj_set_align(ui_SlowCheckbox, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SlowCheckbox, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_color(ui_SlowCheckbox, lv_color_hex(0xD5D2D5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SlowCheckbox, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SlowCheckbox, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_border_color(ui_SlowCheckbox, lv_color_hex(0xFF9929), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_SlowCheckbox, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SlowCheckbox, lv_color_hex(0xFF9929), LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_SlowCheckbox, 255, LV_PART_INDICATOR | LV_STATE_CHECKED);

    ui_MediumCheckbox = lv_checkbox_create(ui_AutoScreen);
    lv_checkbox_set_text(ui_MediumCheckbox, "Medium");
    lv_obj_set_width(ui_MediumCheckbox, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MediumCheckbox, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MediumCheckbox, 11);
    lv_obj_set_y(ui_MediumCheckbox, -11);
    lv_obj_set_align(ui_MediumCheckbox, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_MediumCheckbox, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_color(ui_MediumCheckbox, lv_color_hex(0xD5D2D5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_MediumCheckbox, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_MediumCheckbox, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_border_color(ui_MediumCheckbox, lv_color_hex(0xFF9929), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_MediumCheckbox, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_MediumCheckbox, lv_color_hex(0xFF9929), LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_MediumCheckbox, 255, LV_PART_INDICATOR | LV_STATE_CHECKED);

    ui_FastCheckbox = lv_checkbox_create(ui_AutoScreen);
    lv_checkbox_set_text(ui_FastCheckbox, "Fast");
    lv_obj_set_width(ui_FastCheckbox, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_FastCheckbox, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_FastCheckbox, -8);
    lv_obj_set_y(ui_FastCheckbox, 21);
    lv_obj_set_align(ui_FastCheckbox, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_FastCheckbox, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_color(ui_FastCheckbox, lv_color_hex(0xD5D2D5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_FastCheckbox, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_FastCheckbox, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_border_color(ui_FastCheckbox, lv_color_hex(0xFF9929), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_FastCheckbox, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_FastCheckbox, lv_color_hex(0xFF9929), LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_FastCheckbox, 255, LV_PART_INDICATOR | LV_STATE_CHECKED);

    ui_ManualButton1 = lv_btn_create(ui_AutoScreen);
    lv_obj_set_width(ui_ManualButton1, 81);
    lv_obj_set_height(ui_ManualButton1, 29);
    lv_obj_set_x(ui_ManualButton1, -44);
    lv_obj_set_y(ui_ManualButton1, 65);
    lv_obj_set_align(ui_ManualButton1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ManualButton1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ManualButton1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ManualButton1, lv_color_hex(0xFF9929), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ManualButton1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_ManualButton1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ManualButton1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_ManualButton1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_StartLabel = lv_label_create(ui_ManualButton1);
    lv_obj_set_width(ui_StartLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_StartLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_StartLabel, -3);
    lv_obj_set_y(ui_StartLabel, 1);
    lv_obj_set_align(ui_StartLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_StartLabel, "	START");

    ui_ManualButton3 = lv_btn_create(ui_AutoScreen);
    lv_obj_set_width(ui_ManualButton3, 81);
    lv_obj_set_height(ui_ManualButton3, 29);
    lv_obj_set_x(ui_ManualButton3, 44);
    lv_obj_set_y(ui_ManualButton3, 66);
    lv_obj_set_align(ui_ManualButton3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ManualButton3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ManualButton3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ManualButton3, lv_color_hex(0xFF9929), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ManualButton3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_ManualButton3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ManualButton3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_ManualButton3, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label6 = lv_label_create(ui_ManualButton3);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label6, "Off");

    ui_ManualButton5 = lv_btn_create(ui_AutoScreen);
    lv_obj_set_width(ui_ManualButton5, 60);
    lv_obj_set_height(ui_ManualButton5, 21);
    lv_obj_set_x(ui_ManualButton5, 1);
    lv_obj_set_y(ui_ManualButton5, 102);
    lv_obj_set_align(ui_ManualButton5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ManualButton5, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ManualButton5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ManualButton5, lv_color_hex(0xFF9929), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ManualButton5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_ManualButton5, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ManualButton5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_ManualButton5, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label5 = lv_label_create(ui_ManualButton5);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, "Back");

    lv_obj_add_event_cb(ui_SlowCheckbox, ui_event_SlowCheckbox, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_MediumCheckbox, ui_event_MediumCheckbox, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_FastCheckbox, ui_event_FastCheckbox, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ManualButton1, ui_event_ManualButton1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ManualButton3, ui_event_ManualButton3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ManualButton5, ui_event_ManualButton5, LV_EVENT_ALL, NULL);
    uic_AutoScreen = ui_AutoScreen;
    uic_Dropdown1 = ui_Dropdown1;
    uic_SlowCheckbox = ui_SlowCheckbox;
    uic_MediumCheckbox = ui_MediumCheckbox;
    uic_FastCheckbox = ui_FastCheckbox;
    uic_ManualButton1 = ui_ManualButton1;
    uic_StartLabel = ui_StartLabel;

}

void ui_AutoScreen_screen_destroy(void)
{
    if(ui_AutoScreen) lv_obj_del(ui_AutoScreen);

    // NULL screen variables
    uic_AutoScreen = NULL;
    ui_AutoScreen = NULL;
    ui_Panel4 = NULL;
    uic_Dropdown1 = NULL;
    ui_Dropdown1 = NULL;
    uic_SlowCheckbox = NULL;
    ui_SlowCheckbox = NULL;
    uic_MediumCheckbox = NULL;
    ui_MediumCheckbox = NULL;
    uic_FastCheckbox = NULL;
    ui_FastCheckbox = NULL;
    uic_ManualButton1 = NULL;
    ui_ManualButton1 = NULL;
    uic_StartLabel = NULL;
    ui_StartLabel = NULL;
    ui_ManualButton3 = NULL;
    ui_Label6 = NULL;
    ui_ManualButton5 = NULL;
    ui_Label5 = NULL;

}
