// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SquareLine_Project
#define IR_SEND_PIN 18
#define TONE_PIN 27
#define APPLICATION_PIN 16
#define SEND_PWM_BY_TIMER


#include "ui.h"
#include <IRremote.hpp>




constexpr uint16_t manual_mode_ADDR = 0xF000;
constexpr uint16_t auto_mode_ADDR = 0xF111;

void SetDirection(lv_event_t *e) {
	lv_obj_t *arc = lv_event_get_target(e);
	int value = lv_arc_get_value(arc);
	char buf[32];
	if (value < 100) {
		lv_label_set_text(ui_DirectionLabel, "Left");
		snprintf(buf, sizeof(buf), "%d", 100 - value);
		lv_label_set_text(ui_SpeedLabel, buf);
	} else {
		lv_label_set_text(ui_DirectionLabel, "Right");
		snprintf(buf, sizeof(buf), "%d", value - 100);
		lv_label_set_text(ui_SpeedLabel, buf);
	}
}

void SetDirectionDone(lv_event_t *e) {
	// get the arc value
	lv_obj_t *arc = lv_event_get_target(e);
	int value = lv_arc_get_value(arc);

	// set direction and speed
	uint8_t direction = (value > 100) ? 1 : 0;
	uint8_t speed = (value > 100) ? (value - 100) : (100 - value);
	// create command byte
	uint8_t command = (direction << 7) | (speed & 0x7F);
	Serial.println("Sending a direction");
	// send the ir command
	IrSender.sendNEC(manual_mode_ADDR, command, 4);
	Serial.println("Sent");
}

// Stop the auto mode early
void EndAuto(lv_event_t *e) {
	// set direction and speed
	uint8_t direction = 0;
	uint8_t speed = 0;
	// create command byte
	uint8_t command = (direction << 7) | (speed & 0x7F);

	// send the ir command
	IrSender.sendNEC(manual_mode_ADDR, command, 2);
}

void StartAuto(lv_event_t *e) {
	bool slowChecked = lv_obj_has_state(uic_SlowCheckbox, LV_STATE_CHECKED);
	bool mediumChecked = lv_obj_has_state(uic_MediumCheckbox, LV_STATE_CHECKED);
	bool fastChecked = lv_obj_has_state(uic_FastCheckbox, LV_STATE_CHECKED);
	uint16_t index = lv_dropdown_get_selected(uic_Dropdown1);
	uint8_t mode = 0;
	if (slowChecked)
		mode = 0;
	if (mediumChecked)
		mode = 1;
	if (fastChecked)
		mode = 2;

	uint8_t time = index & 0x03;
	uint8_t command = (mode << 2) | (time & 0x03);

	IrSender.sendNEC(auto_mode_ADDR, command, 2);
}

// If the back button is pressed for manual or auto mode stop
void back_button(lv_event_t *e) {
	// set direction and speed
	uint8_t direction = 0;
	uint8_t speed = 0;
	// create command byte
	uint8_t command = (direction << 7) | (speed & 0x7F);

	// send the ir command
	IrSender.sendNEC(manual_mode_ADDR, command, 2);
}

void sendIRCommand(uint8_t address, uint8_t command) {
	IrSender.sendNEC(address, command, 2);
}