// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * uic_DirectionLabel;
lv_obj_t * uic_SpeedLabel;
lv_obj_t * uic_ManualControlScreen;
lv_obj_t * ui_ManualControlScreen = NULL;
lv_obj_t * ui_Panel3 = NULL;
lv_obj_t * ui_Arc3 = NULL;
lv_obj_t * ui_SpeedLabel = NULL;
lv_obj_t * ui_DirectionLabel = NULL;
lv_obj_t * ui_ManualButton4 = NULL;
lv_obj_t * ui_Label4 = NULL;
// event funtions
void ui_event_Arc3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        SetDirection(e);
    }
    if(event_code == LV_EVENT_RELEASED) {
        SetDirectionDone(e);
    }
}

void ui_event_ManualButton4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_StartMenuScreen, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_StartMenuScreen_screen_init);
        back_button(e);
    }
}

// build funtions

void ui_ManualControlScreen_screen_init(void)
{
    ui_ManualControlScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ManualControlScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel3 = lv_obj_create(ui_ManualControlScreen);
    lv_obj_set_width(ui_Panel3, 240);
    lv_obj_set_height(ui_Panel3, 240);
    lv_obj_set_align(ui_Panel3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel3, 100, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Arc3 = lv_arc_create(ui_ManualControlScreen);
    lv_obj_set_width(ui_Arc3, 219);
    lv_obj_set_height(ui_Arc3, 219);
    lv_obj_set_x(ui_Arc3, -3);
    lv_obj_set_y(ui_Arc3, 0);
    lv_obj_set_align(ui_Arc3, LV_ALIGN_CENTER);
    lv_arc_set_range(ui_Arc3, 0, 200);
    lv_arc_set_value(ui_Arc3, 100);
    lv_arc_set_bg_angles(ui_Arc3, 135, 45);
    lv_arc_set_mode(ui_Arc3, LV_ARC_MODE_SYMMETRICAL);
    lv_obj_set_style_arc_color(ui_Arc3, lv_color_hex(0xD1D1D1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_Arc3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_Arc3, 40, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_Arc3, true, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_Arc3, lv_color_hex(0xF89B29), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_Arc3, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_Arc3, 40, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_img_src(ui_Arc3, &ui_img_1501055002, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Arc3, lv_color_hex(0xF89B29), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Arc3, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_SpeedLabel = lv_label_create(ui_ManualControlScreen);
    lv_obj_set_width(ui_SpeedLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SpeedLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_SpeedLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SpeedLabel, "0");
    lv_obj_set_style_text_color(ui_SpeedLabel, lv_color_hex(0xD5D2D5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SpeedLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SpeedLabel, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DirectionLabel = lv_label_create(ui_ManualControlScreen);
    lv_obj_set_width(ui_DirectionLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DirectionLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DirectionLabel, -3);
    lv_obj_set_y(ui_DirectionLabel, 48);
    lv_obj_set_align(ui_DirectionLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_DirectionLabel, "None");
    lv_obj_set_style_text_color(ui_DirectionLabel, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_DirectionLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_DirectionLabel, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ManualButton4 = lv_btn_create(ui_ManualControlScreen);
    lv_obj_set_width(ui_ManualButton4, 60);
    lv_obj_set_height(ui_ManualButton4, 21);
    lv_obj_set_x(ui_ManualButton4, 1);
    lv_obj_set_y(ui_ManualButton4, 98);
    lv_obj_set_align(ui_ManualButton4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ManualButton4, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ManualButton4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ManualButton4, lv_color_hex(0xFF9929), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ManualButton4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_ManualButton4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ManualButton4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_ManualButton4, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label4 = lv_label_create(ui_ManualButton4);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "Back");

    lv_obj_add_event_cb(ui_Arc3, ui_event_Arc3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ManualButton4, ui_event_ManualButton4, LV_EVENT_ALL, NULL);
    uic_ManualControlScreen = ui_ManualControlScreen;
    uic_SpeedLabel = ui_SpeedLabel;
    uic_DirectionLabel = ui_DirectionLabel;

}

void ui_ManualControlScreen_screen_destroy(void)
{
    if(ui_ManualControlScreen) lv_obj_del(ui_ManualControlScreen);

    // NULL screen variables
    uic_ManualControlScreen = NULL;
    ui_ManualControlScreen = NULL;
    ui_Panel3 = NULL;
    ui_Arc3 = NULL;
    uic_SpeedLabel = NULL;
    ui_SpeedLabel = NULL;
    uic_DirectionLabel = NULL;
    ui_DirectionLabel = NULL;
    ui_ManualButton4 = NULL;
    ui_Label4 = NULL;

}
