// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_MANUALCONTROLSCREEN_H
#define UI_MANUALCONTROLSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_ManualControlScreen
extern void ui_ManualControlScreen_screen_init(void);
extern void ui_ManualControlScreen_screen_destroy(void);
extern lv_obj_t * ui_ManualControlScreen;
extern lv_obj_t * ui_Panel3;
extern void ui_event_Arc3(lv_event_t * e);
extern lv_obj_t * ui_Arc3;
extern lv_obj_t * ui_SpeedLabel;
extern lv_obj_t * ui_DirectionLabel;
extern void ui_event_ManualButton4(lv_event_t * e);
extern lv_obj_t * ui_ManualButton4;
extern lv_obj_t * ui_Label4;
// CUSTOM VARIABLES
extern lv_obj_t * uic_ManualControlScreen;
extern lv_obj_t * uic_SpeedLabel;
extern lv_obj_t * uic_DirectionLabel;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

