// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_STARTMENUSCREEN_H
#define UI_STARTMENUSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_StartMenuScreen
extern void ui_StartMenuScreen_screen_init(void);
extern void ui_StartMenuScreen_screen_destroy(void);
extern lv_obj_t * ui_StartMenuScreen;
extern lv_obj_t * ui_Panel1;
extern void ui_event_ManualButton(lv_event_t * e);
extern lv_obj_t * ui_ManualButton;
extern lv_obj_t * ui_Label1;
extern void ui_event_AutoButton(lv_event_t * e);
extern lv_obj_t * ui_AutoButton;
extern lv_obj_t * ui_Label2;
// CUSTOM VARIABLES
extern lv_obj_t * uic_StartMenuScreen;
extern lv_obj_t * uic_ManualButton;
extern lv_obj_t * uic_AutoButton;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

