// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * uic_AutoButton;
lv_obj_t * uic_ManualButton;
lv_obj_t * uic_StartMenuScreen;
lv_obj_t * ui_StartMenuScreen = NULL;
lv_obj_t * ui_Panel1 = NULL;
lv_obj_t * ui_ManualButton = NULL;
lv_obj_t * ui_Label1 = NULL;
lv_obj_t * ui_AutoButton = NULL;
lv_obj_t * ui_Label2 = NULL;
// event funtions
void ui_event_ManualButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ManualControlScreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_ManualControlScreen_screen_init);
    }
}

void ui_event_AutoButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_AutoScreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_AutoScreen_screen_init);
    }
}

// build funtions

void ui_StartMenuScreen_screen_init(void)
{
    ui_StartMenuScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_StartMenuScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel1 = lv_obj_create(ui_StartMenuScreen);
    lv_obj_set_width(ui_Panel1, 240);
    lv_obj_set_height(ui_Panel1, 240);
    lv_obj_set_align(ui_Panel1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel1, 100, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ManualButton = lv_btn_create(ui_StartMenuScreen);
    lv_obj_set_width(ui_ManualButton, 201);
    lv_obj_set_height(ui_ManualButton, 50);
    lv_obj_set_x(ui_ManualButton, -2);
    lv_obj_set_y(ui_ManualButton, -32);
    lv_obj_set_align(ui_ManualButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ManualButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ManualButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ManualButton, lv_color_hex(0xFF9929), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ManualButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_ManualButton, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ManualButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_ManualButton, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label1 = lv_label_create(ui_ManualButton);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "Manual");

    ui_AutoButton = lv_btn_create(ui_StartMenuScreen);
    lv_obj_set_width(ui_AutoButton, 200);
    lv_obj_set_height(ui_AutoButton, 50);
    lv_obj_set_x(ui_AutoButton, 0);
    lv_obj_set_y(ui_AutoButton, 33);
    lv_obj_set_align(ui_AutoButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_AutoButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_AutoButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_AutoButton, lv_color_hex(0xFF9929), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_AutoButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_AutoButton, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_AutoButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_AutoButton, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label2 = lv_label_create(ui_AutoButton);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "Auto");

    lv_obj_add_event_cb(ui_ManualButton, ui_event_ManualButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_AutoButton, ui_event_AutoButton, LV_EVENT_ALL, NULL);
    uic_StartMenuScreen = ui_StartMenuScreen;
    uic_ManualButton = ui_ManualButton;
    uic_AutoButton = ui_AutoButton;

}

void ui_StartMenuScreen_screen_destroy(void)
{
    if(ui_StartMenuScreen) lv_obj_del(ui_StartMenuScreen);

    // NULL screen variables
    uic_StartMenuScreen = NULL;
    ui_StartMenuScreen = NULL;
    ui_Panel1 = NULL;
    uic_ManualButton = NULL;
    ui_ManualButton = NULL;
    ui_Label1 = NULL;
    uic_AutoButton = NULL;
    ui_AutoButton = NULL;
    ui_Label2 = NULL;

}
